import { Dimensions, StyleSheet } from "react-native";
import Fonts from "../../constants/font";
const { width } = Dimensions.get("window");
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    elevation: 2,
  },
  headerBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    height: 180,

  },
  headerTitleContainer: {
    position: "absolute",
    top: 90,
    left: 0,
    right: 0,
    bottom: 0,
    height: 180,
    zIndex: 9999,
  },
  backgroundImage: {
    width: "100%",
    height: "90%",
    resizeMode: "stretch",
    borderBottomEndRadius: 35,
  },
  headerContent: {
    // marginRight: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 45,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,

  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EFEAD6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  headerTitle: {
    fontFamily: Fonts.Montserrat.SemiBold,
    fontSize: 16,
    color: '#333',
    paddingHorizontal: 16,
    paddingVertical: 12,

  },
  headerRight: {
    flexDirection: 'row',
  },
  iconButton: {
    padding: 5,
    marginLeft: 12,
  },
  scrollView: {
    flex: 1,
    // marginBottom: 100,
  },
  searchContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginTop: 15,
    // backgroundColor: '#fff',
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 24,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginRight: 8,
    borderColor: '#E5E5E5',
    borderWidth: 1,
  },
  searchPlaceholder: {
    fontFamily: Fonts.Montserrat.Regular,
    marginLeft: 8,
    color: '#999',
    fontSize: 14,

  },
  searchButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationButton: {
    width: 40,
    height: 40,

    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 50,
  },
  balanceContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  balanceCard: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    position: 'relative',
  },
  balanceCardPrimary: {
    backgroundColor: '#4CAF50',
  },
  balanceCardSecondary: {
    backgroundColor: '#2196F3',
  },
  balanceLabel: {
    color: '#fff',
    fontFamily: Fonts.Montserrat.Regular,
    fontSize: 14,
  },
  balanceAmount: {
    fontFamily: Fonts.DelaGothicOne,
    color: '#fff',
    fontSize: 16,
    marginTop: 4,
  },
  addIcon: {
    position: 'absolute',
    top: 12,
    right: 12,
  },
  promotionBanner: {
    margin: 16,
    backgroundColor: '#E8F5E8',

    flexDirection: 'row',
    alignItems: 'center',
  },
  promotionContent: {
    flex: 1,
  },
  promotionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2E7D32',
  },
  promotionSubtitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2E7D32',
    marginTop: 2,
  },
  promotionDescription: {
    fontSize: 12,
    color: '#black',
    marginTop: 4,
  },
  promotionStats: {
    flexDirection: 'row',
    marginTop: 8,
    gap: 20,
  },
  statItem: {
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2E7D32',
  },
  statLabel: {
    fontSize: 10,
    color: '#black',
  },
  promotionButton: {
    backgroundColor: '#4CAF50',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  promotionButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
  },
  promotionImage: {
    width: width * 0.925,
    // height: 60,
    borderRadius: 24,
    aspectRatio: 16 / 9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deliveryIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  section: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: Fonts.DelaGothicOne,
    color: '#333',
    marginBottom: 12,
  },
  offerGrid: {
    flexDirection: 'row',
    gap: 12,
    // paddingHorizontal: 16,
  },
  offerCard: {
    width: 200,
    height: 200,
    borderRadius: 12,
    overflow: 'hidden',
  },
  offerImage: {
    height: "100%",
    // height: 60,
    aspectRatio: 16 / 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  offerImageContainer: {
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 6,
    marginBottom: 8,
  },
  offerTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
    marginBottom: 2,
  },
  offerSubtitle: {
    fontSize: 12,
    color: '#black',
    marginBottom: 4,
  },
  offerDiscount: {
    fontSize: 12,
    color: '#4CAF50',
    fontWeight: '500',
  },
  nearbyCard: {
    flexDirection: 'row',
    backgroundColor: '#F1F5EA',
    borderRadius: 8,
    padding: 12,
    elevation: 2,
    alignItems: 'center',
    gap: 12,
  },
  nearbyImageContainer: {
    width: 60,
    height: 60,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  nearbyInfo: {
    marginRight: 45,
  },
  nearbyTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    marginBottom: 4,
  },
  nearbyAddress: {
    fontSize: 12,
    color: '#black',
    marginBottom: 6,
  },
  nearbyTags: {
    flexDirection: 'row',
    gap: 6,
  },
  tag: {
    backgroundColor: '#E3F2FD',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  tagText: {
    fontSize: 10,
    color: '#1976D2',
  },
  favoriteButton: {
    padding: 8,
  },
  challengeCard: {
    flexDirection: 'row',
    backgroundColor: '#FFF3E0',
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
    height: 135,
    gap: 120,
  },
  challengeContent: {
    // flex: 1,
  },
  challengeTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
    marginBottom: 4,
  },
  challengeSubtitle: {
    fontSize: 14,
    color: '#black',
    marginBottom: 8,
  },
  challengeButton: {
    backgroundColor: '#333',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 24,
    alignSelf: 'flex-start',
  },
  challengeButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
   
  },
  challengeIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  challengeImageContainer: {
    width: 100,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  challengeImage: {
    width: "100%",
    // height: 70,
  },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    paddingVertical: 12,
    elevation: 8,
    justifyContent: 'space-around',
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
});